spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub
spring.datasource.username=manikanta
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.error.include-stacktrace=never
server.error.include-message=never

jwt.secret=eventhubsecretkeyeventhubsecretkeyeventhubsecretkey
jwt.expiration=3600000
jwt.refresh-expiration=604800000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

upload.directory=uploads
upload.base-url=http://localhost:8080/api/upload/files